# Generated by Django 5.2 on 2025-05-03 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenterPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DataCenterSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('below_amount', models.IntegerField()),
                ('above_amount', models.IntegerField()),
                ('minimize', models.IntegerField()),
                ('maximize', models.IntegerField()),
                ('unconstrained', models.IntegerField()),
                ('unit', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('is_input', models.BooleanField()),
                ('is_output', models.BooleanField()),
                ('unit', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DataCenterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.datacenterspecs')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='core.module')),
            ],
        ),
    ]
