# Generated by Django 5.2 on 2025-05-03 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_datacenterspecs_name_alter_module_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='module',
            name='unit',
        ),
        migrations.CreateModel(
            name='ModuleAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core.module')),
            ],
        ),
    ]
