# Generated by Django 5.2 on 2025-05-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_module_amount_remove_module_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='is_input',
        ),
        migrations.RemoveField(
            model_name='module',
            name='is_output',
        ),
        migrations.AddField(
            model_name='moduleattribute',
            name='is_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moduleattribute',
            name='is_output',
            field=models.BooleanField(default=False),
        ),
    ]
