# Generated by Django 5.2 on 2025-05-03 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_module_is_input_remove_module_is_output_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenterComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='datacentervalue',
            name='spec',
        ),
        migrations.AddField(
            model_name='activemodule',
            name='data_center_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_modules', to='core.datacentercomponent'),
        ),
        migrations.AddField(
            model_name='datacentervalue',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.datacentercomponent'),
        ),
        migrations.CreateModel(
            name='DataCenterComponentAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('below_amount', models.IntegerField()),
                ('above_amount', models.IntegerField()),
                ('minimize', models.IntegerField()),
                ('maximize', models.IntegerField()),
                ('unconstrained', models.IntegerField()),
                ('unit', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core.datacentercomponent')),
            ],
        ),
        migrations.DeleteModel(
            name='DataCenterSpecs',
        ),
    ]
