# Generated by Django 5.2 on 2025-05-03 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_datacentercomponent_remove_datacentervalue_spec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('space_x', models.IntegerField(default=1000)),
                ('space_y', models.IntegerField(default=500)),
            ],
        ),
        migrations.AddField(
            model_name='datacentervalue',
            name='data_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.datacenter'),
        ),
    ]
