# Generated by Django 5.2 on 2025-05-03 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_datacenter_datacentervalue_data_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacentercomponent',
            name='data_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.datacenter'),
        ),
    ]
