# Generated by Django 5.2 on 2025-05-03 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_datacentercomponent_data_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='activemodule',
            name='data_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_modules', to='core.datacenter'),
        ),
    ]
