# Generated by Django 5.2 on 2025-05-03 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_activemodule_data_center'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataCenterPoints',
            new_name='Point',
        ),
        migrations.RemoveField(
            model_name='activemodule',
            name='x',
        ),
        migrations.RemoveField(
            model_name='activemodule',
            name='y',
        ),
        migrations.AddField(
            model_name='activemodule',
            name='point',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='active_modules', to='core.point'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datacenter',
            name='points',
            field=models.ManyToManyField(blank=True, related_name='data_centers', to='core.point'),
        ),
    ]
