# Generated by Django 5.2 on 2025-05-03 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_datacenterpoints_point_remove_activemodule_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='data_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.datacenter'),
        ),
    ]
